### ISSUE TITLE
Flud from the plugin

### ISSUE THREAD

**Issue by ccyounga** [RefracDevelopment/SimpleStaffChat2#12]
At the time when the player leaves the game, the system starts flooding with messages that he has left.

[14:20:59 INFO]: [-]  {#DA2A18>}[Основатель]{#DA2A18<} younga вышел из игры.
[14:20:59 INFO]: [-]  {#DA2A18>}[Основатель]{#DA2A18<} younga вышел из игры.
[14:20:59 INFO]: [-]  {#DA2A18>}[Основатель]{#DA2A18<} younga вышел из игры.

The number of flood lines is always different, sometimes there can be one line, sometimes there are ten of them.

**Comment by Refrac** [comment]
This will be fixed in the next release trying to get some other things fixed first.

**Comment by ccyounga** [comment]
Okay, we're waiting.

**Comment by Refrac** [comment]
@ccyounga This has been fixed in 2.4:
https://www.spigotmc.org/resources/simplestaffchat2-1-7-1-19.91883/update?update=464149
https://polymart.org/resource/simplestaffchat2-1-7-1-19.1173/updates?update=16597
https://songoda.com/product/simplestaffchat-17-116-staffchat/version/2.4
https://www.mc-market.org/resources/22491/updates#resource-update-86729
